data: 'shrec'
data_param:
  train_data_param:
    data_path: ../data/shrec/train_skeleton.pkl
    label_path: ../data/shrec/train_label_28.pkl
    random_choose: True
    center_choose: False
    window_size: 20
    final_size: 20
    num_skip_frame:
    decouple_spatial: True
  val_data_param:
    data_path: ../data/shrec/val_skeleton.pkl
    label_path: ../data/shrec/val_label_28.pkl
    random_choose: False
    center_choose: False
    window_size: 20
    final_size: 20
    num_skip_frame:
    decouple_spatial: True

model: 'sgn_ada'
model_param:
  seg: 20
  num_joints: [1, 11, 22]
  dim: 256
  policy_kernel: 3
  policy_dilate: 1
  gcn_types: ['small', 'big']
  adaptive_transform: [True, True, True]
  policy_type: 'tconv'
  init_type: 'random'  # fix actions in init stage
  tau: 5
  tau_decay: -0.045
  tau_type: 'linear'
  pre_trains: [
                 '../pretrain_models/shrec28/single_sgn_jpt1_small_bone.state',
                 '../pretrain_models/shrec28/single_sgn_jpt1_big_bone.state',
                 '../pretrain_models/shrec28/single_sgn_jpt11_small_bone.state',
                 '../pretrain_models/shrec28/single_sgn_jpt11_big_bone.state',
                 '../pretrain_models/shrec28/single_sgn_jpt22_small_bone.state',
                 '../pretrain_models/shrec28/single_sgn_jpt22_big_bone.state',
  ]
  init_num: 100  # init temporal net and fc


pipeline: 'classify_ada'
pipeline_param:

loss: 'smooth_CE_FLOPS'
loss_param:
  label_smoothing_num: 0.1
  alpha: 4
  freeze_alpha: 0
  warm_epoch: 5
  beta: 0
  begin_action: 1

lr_scheduler: 'reduce_by_epoch'
lr_scheduler_param:
  step: [60, 90, 110]
  lr_decay_ratio: 0.1
  warm_up_epoch: 0
freeze_keys: [['spa_nets', 30], ['transforms', 30]]
lr_multi_keys: []

optimizer: 'adam'
optimizer_param:
  lr: 0.001
  weight_decay: 0.0001
#  momentum: 0.9

seed: 1
eval: False
class_num: 28
batch_size: 64
worker: 32
pin_memory: False
max_epoch: 120
num_epoch_per_save: 200
model_saved_name: '../work_dir/shrec28/sgnadapre_alpha4warm5_policyran_lineartau5_transformfix30_models6fix30_lr0001_bone'
last_model:
pre_trained_model:
ignore_weights: []
val_first: False
device_id: [0]
cuda_visible_device: '0'
debug: False
