data: 'ntu_skeleton'
data_param:
  train_data_param:
    data_path: ../data/ntu60/CS/train_data.npy
    label_path: ../data/ntu60/CS/train_label.pkl
    random_choose: True
    center_choose: False
    window_size: 20
    final_size: 20
    num_skip_frame:
    decouple_spatial: False
    rotation: [[-17, 17],[-17, 17],[-17, 17]]
    turn2to1: False
  val_data_param:
    data_path: ../data/ntu60/CS/test_data.npy
    label_path: ../data/ntu60/CS/test_label.pkl
    random_choose: False
    center_choose: False
    window_size: 20
    final_size: 20
    num_skip_frame:
    decouple_spatial: False
    eval: False
    turn2to1: False
model: 'sgn_ada'
model_param:
  seg: 20
  num_joints: [1, 9, 25]
  dim: 256
  policy_kernel: 3
  policy_dilate: 1
  gcn_types: ['small', 'big']
  adaptive_transform: [True, True, True]
  policy_type: 'tconv'
  init_type: 'random'  # fix actions in init stage
  tau: 5
  tau_decay: -0.045
  tau_type: 'linear'
  #  pre_trains: [
  #      '../pretrain_models/single_sgn_jpt5.state',
  #      '../pretrain_models/single_sgn_jpt9.state',
  #      '../pretrain_models/single_sgn_jpt13.state',
  #      '../pretrain_models/single_sgn_jpt17.state',
  #      '../pretrain_models/single_sgn_jpt21.state',
  #      '../pretrain_models/single_sgn_jpt25.state',
  #    ]
  init_num: 100


pipeline: 'classify_ada'
pipeline_param:

loss: 'smooth_CE_FLOPS'
loss_param:
  label_smoothing_num: 0.1
  alpha: 4
  freeze_alpha: 0
  warm_epoch: 5
  beta: 0
  begin_action: 1

lr_scheduler: 'reduce_by_epoch'
lr_scheduler_param:
  step: [60, 90, 110]
  lr_decay_ratio: 0.1
  warm_up_epoch: 0
freeze_keys: [['transforms', 30]]
lr_multi_keys: []

optimizer: 'adam'
optimizer_param:
  lr: 0.001
  weight_decay: 0.0001

seed: 1
eval: False
class_num: 60
batch_size: 64
worker: 32
pin_memory: False
max_epoch: 120
num_epoch_per_save: 200
model_saved_name: '../work_dir/ntu60/sgnada_alpha4warm5_policyran_lineartau5_transformfix30_models6_lr0001'
last_model:
pre_trained_model:
ignore_weights: []
val_first: False
device_id: [0]
cuda_visible_device: '7'
debug: False
